### PR TITLE
Make CI run on all PRs and fix build

### LINKED ISSUE #2: openvalidation-rest fails to build
## Expected Behavior
````
mvn clean package
....
[INFO] ---------------< io.openvalidation:openvalidation-rest >----------------
[INFO] Building openvalidation-rest 0.0.1                                 [8/9]
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for io.openvalidation:openvalidation-core:jar:1.0-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for io.openvalidation:openvalidation-common:jar:1.0-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Build Tools 1.0 .................................... SUCCESS [  2.051 s]
[INFO] openVALIDATION 0.0.1 ............................... SUCCESS [  1.179 s]
[INFO] openvalidation-common 0.0.1 ........................ SUCCESS [ 15.094 s]
[INFO] openvalidation-antlr 0.0.1 ......................... SUCCESS [ 13.005 s]
[INFO] openvalidation-generation 0.0.1 .................... SUCCESS [  9.363 s]
[INFO] openvalidation-core 0.0.1 .......................... SUCCESS [02:06 min]
[INFO] openvalidation-cli 0.0.1 ........................... SUCCESS [  5.497 s]
[INFO] openvalidation-rest 0.0.1 .......................... FAILURE [  0.578 s]
[INFO] openvalidation-integration-generator 0.0.1 ......... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:54 min
[INFO] Finished at: 2019-09-03T07:59:02+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project openvalidation-rest: Could not resolve dependencies for project io.openvalidation:openvalidation-rest:jar:0.0.1: The following artifacts could not be resolved: io.openvalidation:openvalidation-core:jar:1.0-SNAPSHOT, io.openvalidation:openvalidation-common:jar:1.0-SNAPSHOT: Failure to find io.openvalidation:openvalidation-core:jar:1.0-SNAPSHOT in https://jcenter.bintray.com/ was cached in the local repository, resolution will not be reattempted until the update interval of jcenter-snapshots has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :openvalidation-rest
````

## Your Environment
Manjaro linux,
mvn 3.6.1, java 1.8.0_222

### PR DESCRIPTION
**Pull request by sbischoff-ai**
We want to run build checks on all PRs.

Also fixes #2 and closes #3 because the build needs to run through.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause compatibility issues)
- [x] DevOps change (fix or alteration in a build pipeline or config file)

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
This might require to #3 to be merged first.

**Comment by matthiaskrgr** [comment]
Uhm what?
````
##[section]Starting: PublishPipelineArtifact
==============================================================================
Task         : Publish Pipeline Artifact
Description  : Publish Pipeline Artifact
Version      : 0.139.0
Author       : Microsoft Corporation
Help         : Publish a local directory or file as a named artifact for the current pipeline.
==============================================================================
##[error]Path not exist: /home/vsts/work/1/s/openvalidation-openapi-generator/target/ov-openapi-generator-cli.jar
##[section]Finishing: PublishPipelineArtifact
````

**Comment by sbischoff-ai** [comment]
> Uhm what?
> 
> ```
> ##[section]Starting: PublishPipelineArtifact
> ==============================================================================
> Task         : Publish Pipeline Artifact
> Description  : Publish Pipeline Artifact
> Version      : 0.139.0
> Author       : Microsoft Corporation
> Help         : Publish a local directory or file as a named artifact for the current pipeline.
> ==============================================================================
> ##[error]Path not exist: /home/vsts/work/1/s/openvalidation-openapi-generator/target/ov-openapi-generator-cli.jar
> ##[section]Finishing: PublishPipelineArtifact
> ```

Yeah, that's a legacy part of that pipeline. Removing it.

**Comment by matthiaskrgr** [comment]
I think we should still check master branch in ci:

given master is at state A
and we have 2 PRs branching off it
master---pr1
master---pr2

pr1 works with master
pr2 works with master

pr1 gets merged
now master includes pr1 which breaks tests of pr2
pr2 also gets merged because CI was green from the "old" state (A) of master
now master would fail in CI but I don't think we would notice with this pr included?

**Comment by sbischoff-ai** [comment]
That can't happen because changes on master invalidate the build.

**Comment by matthiaskrgr** [comment]
Ok!

**Pull request merged**
